# Generated by Django 5.2 on 2025-05-02 11:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email manzil')),
                ('user_type', models.CharField(choices=[('employer', 'Ish beruvchi'), ('candidate', 'Nomzod'), ('admin', 'Administrator')], max_length=20, verbose_name='foydalanuvchi turi')),
                ('is_verified', models.BooleanField(default=False, help_text='Admin tomonidan tasdiqlangan', verbose_name='tasdiqlangan')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronymic', models.CharField(max_length=100, verbose_name='otasining ismi')),
                ('education', models.CharField(choices=[('higher', 'Oliy'), ('secondary_higher', 'Tayanch oliy'), ('secondary_special', "O'rta maxsus")], max_length=50, verbose_name="ma'lumoti")),
                ('specialization', models.CharField(max_length=255, verbose_name='mutaxassisligi')),
                ('residential_address', models.CharField(max_length=255, verbose_name='doimiy yashash manzili')),
                ('passport_number', models.CharField(max_length=20, verbose_name='pasport raqami')),
                ('passport_pdf', models.FileField(blank=True, null=True, upload_to='passports/', verbose_name='pasport pdf nusxasi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='tashkilot nomi')),
                ('company_address', models.CharField(max_length=255, verbose_name='tashkilot manzili')),
                ('position', models.CharField(max_length=100, verbose_name='lavozimi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
